-- Semilla de fichas desde app/assets/geojson/edificios.json.
-- Solo código y nombre. No pisa una ficha que el admin ya haya editado.

insert into public.places (id, name, kind)
values
  ('A1', 'Agora', 'building'),
  ('A2', 'Fondo acumulativo', 'building'),
  ('B1', 'Herbario CUVC "Luis Sigifredo Espinal-Tascón"', 'building'),
  ('B13', 'EISC - Escuela de ingeniería de sistemas y computación', 'building'),
  ('B14', 'Servicio Geológico Colombiano - Ingeominas', 'building'),
  ('B15', 'Laboratorio de Fluidos e Hidráulica', 'building'),
  ('B16', 'Gestion documental', 'building'),
  ('B17', 'Servicios Varios/ Bodega Jardinería y Vivero', 'building'),
  ('B18', 'Taller de Mantenimiento/ Bodega Inventario', 'building'),
  ('B19', 'Laboratorio 3 Estación experimental Biología', 'building'),
  ('B2', 'Espacio IVIultipropósito - Contenedores', 'building'),
  ('B20', 'Laboratorio 2 Estación experimental Biología', 'building'),
  ('B21', 'Laboratorio 1 Estación experimental Biología', 'building'),
  ('B23', 'CECIM (Centro de Investigación para la Enseñanza de las Ciencias Naturales y las Matematicas)', 'building'),
  ('B24', 'Unidad Transitoria de Basuras', 'building'),
  ('C5', 'CDU - Gimnasio', 'building'),
  ('C7', 'Edificio C7', 'building'),
  ('C9', 'Camerinos', 'building'),
  ('D1', 'Escuela de Arquitectura', 'building'),
  ('D10', 'Edificio Carlos Restrepo Acuña', 'building'),
  ('D12', 'Facultad de Ciencias Sociales y Económicas.', 'building'),
  ('D13', 'Edificio Josué Angel', 'building'),
  ('D14', 'Restaurante Universitario / Cafetería Central', 'building'),
  ('D16', 'Tulpa del Lago', 'building'),
  ('D17', 'Coliseo Alberto León Betancur', 'building'),
  ('D2', 'Edificio Laboratorio de Arquitectura', 'building'),
  ('D4', 'Instituto de Educación y Pedagogía', 'building'),
  ('D5', 'Departamento de Diseño', 'building'),
  ('D6', 'Escuela de Comunicación Social', 'building'),
  ('D7', 'Departamento de Geografía', 'building'),
  ('D8', 'Edificio Estanislao Zuleta', 'building'),
  ('E1', 'Administración Central', 'building'),
  ('E10', 'Aulas Departamento de Artes Visuales / Departamento de Artes Escénicas', 'building'),
  ('E11', 'Departamento de Diseño', 'building'),
  ('E12', 'Departamento de Diseño', 'building'),
  ('E15', 'Tulio Ramírez', 'building'),
  ('E17', 'Escuela de Ciencias del Lenguaje', 'building'),
  ('E18', 'Edificio de Medios / DINTEV / CREE', 'building'),
  ('E19', 'Biblioteca Central Mario Carvajal', 'building'),
  ('E20', 'Facultad de Ciencias Naturales y Exactas', 'building'),
  ('E22', 'Torre de Ingeniería', 'building'),
  ('E23', 'Edificio Espiritu Santo Potes', 'building'),
  ('E24', 'Complejo Auditorios', 'building'),
  ('E26', 'Álvaro Escobar Navia – Aulas', 'building'),
  ('E27', 'Escuela de Ingeniería Química', 'building'),
  ('E28', 'Escuela de Ingeniería Química', 'building'),
  ('E29', 'Planta Piloto de Ingeniería Química', 'building'),
  ('E30', 'Escuela de Ingeniería Química / Laboratorio de Análisis Instrumental', 'building'),
  ('E32', 'Escuela de Ingeniería de Alimentos', 'building'),
  ('E33', 'Escuela de Ingeniería Mecánica', 'building'),
  ('E37', 'Escuela de Ingeniería de Recursos Naturales y del Ambiente', 'building'),
  ('E38', 'Centro de Estudios Facultad de Ingeniería.', 'building'),
  ('E39', 'Escuela de Ingeniería de Recursos Naturales y del Ambiente', 'building'),
  ('E42', 'Escuela de Ingeniería Mecánica', 'building'),
  ('E43', 'Escuela de Ingeniería Civil y Geomática', 'building'),
  ('E44', 'Escuela de Ingeniería de Materiales', 'building'),
  ('E46', 'Escuela de Ingeniería de Materiales', 'building'),
  ('E47', 'Escuela de Ingeniería de Materiales', 'building'),
  ('E48', 'Escuela de Ingeniería Civil y Geomática', 'building'),
  ('E49', 'Escuela de Estadística', 'building'),
  ('E50', 'Laboratorio de Alta Tensión', 'building'),
  ('E52', 'Escuela de Ingeniería Eléctrica y Electrónica', 'building'),
  ('E53', 'Escuela de Ingeniería Eléctrica y Electrónica', 'building'),
  ('E55', 'Escuela de Ingeniería Eléctrica y Electrónica', 'building'),
  ('E56', 'Escuela de Ingeniería Industrial', 'building'),
  ('E6', 'Aulas Escuela de Música /Taller Departamento Artes Visuales', 'building'),
  ('E7', 'Aulas Escuela de Música /Aulas Departamento de Artes Escénicas', 'building'),
  ('E8', 'Aulas Escuela de Música /Aulas Departamento de Artes Escénicas', 'building'),
  ('E9', 'Aulas Departamento de Artes Escénicas', 'building')
on conflict (id) do nothing;
